version: '3.4'

services:
  mock_server:
    build:
      context: .
      dockerfile: docker/Dockerfile_mock_server
    healthcheck:
      test: curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/healthcheck || exit 1
      interval: 30s
      timeout: 30s
      retries: 3

  py_parse_sber:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/opt/app
    depends_on:
      - mock_server

