name: Publish Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: niccolum/py_parse_sber/py_parse_sber
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        snapshot: true
        registry: docker.pkg.github.com
        dockerfile: docker/Dockerfile